### ISSUE TITLE
Random Crashing on 26.2

### ISSUE THREAD

**Issue by Queen-of-Ruin** [Fourmisain/IndyPets#35]
I keep randomly getting the following error log when at my base, even if my parrots aren't around water:

java.lang.NoSuchMethodError: 'net.minecraft.world.phys.Vec3 net.minecraft.core.BlockPos.getCenter()'
	at knot//net.minecraft.world.entity.ai.goal.WaterAvoidingRandomFlyingGoal.modifyExpressionValue$bpc000
$indypets$dontStrayFromHome(WaterAvoidingRandomFlyingGoal.java:526)
	at knot//net.minecraft.world.entity.ai.goal.WaterAvoidingRandomFlyingGoal.getPosition(WaterAvoidingRandomFlyingGoal.java:17)

The game just abruptly closes. Worked fine on my 26.1.2 client. Any idea what could be causing this?

**Comment by Almtesh** [comment]
I have the same issue on a server, I disabled the mod and it works again.
I think this is a problem with the pathfinding of the parrot, that is very different of the one of wolves and cats, mainly because the parrot can fly.

By the way, I tried to add the parrot to the blacklist in `config/indypets.json`, but it does not work:
```json
{
  "regularInteract": true,
  "sneakInteract": true,
  "silentMode": false,
  "homeRadius": 16,
  "innerHomePercentage": 0.0,
  "whistleRadius": 96,
  "blocklist": [
    "mythicmounts:*",
    "lovely_snails:snail",
    "minecraft:parrot",
    "minecraft:zombie_nautilus",
    "minecraft:nautilus"
  ],
  "interactBlocklist": [
    "cobblemon:*"
  ],
  "hornConfig": {},
  "hornState": false,
  "positionedWhistleSound": false,
  "vanillaPlayerConfigs": {
  }
}
```
I can still set parrot independent.

**Comment by Fourmisain** [comment]
Dang, I tested the mod on 26.2, just not with parrots!

Fixed in 1.5.4!

**Comment by Fourmisain** [comment]
Btw, about this

> I tried to add the parrot to the blacklist in config/indypets.json, but it does not work:
> (...)
> I can still set parrot independent.

The server config only applies to vanilla players.
When a player has the mod installed client side, it will send their config to the server and the server will respect their settings over its own.
(In other words, this would have worked if every player had blocked parrots.)

P.S.
Also had no idea that Nautiluses actually tameable, I thought they worked just like horses.
Will have a look into maybe adding them to the block list by default.

**Comment by Almtesh** [comment]
I tried with my client, it does not have the mod. I think nobody on the server uses the mod on their client.
The `vanillaPlayerConfigs` I put in my message was emptied before posting.

**Comment by Fourmisain** [comment]
Ohhh!

I just did some testing with a server that blocks parrots, joined with a vanilla client and couldn't reproduce your issue (i.e. parrots were blocked just fine).
I was gonna say maybe you hadn't rebooted the server so the settings didn't apply and I thought the `vanillaPlayerConfigs` shouldn't matter anyway as they don't contain a block list.

But here's the thing:
The `vanillaPlayerConfigs` *don't contain a block list!*
If there is a player config, vanilla or not, the server will use that over its own - and having no block list means it'll use the default one, hence parrots won't be blocked!

That's quite a niche bug if I ever saw one!
Will need to think how to solve that one - this might require a complete rewrite of the config logic.

**Comment by Fourmisain** [comment]
Fixed the config bug and blocked nautiluses by default in 1.5.5 and 1.4.13! (Backporting took ages...)
Also fixed another bug with vanilla only players: If they didn't have their own config, the horn toggle would be shared among them.

I'll always recommend to install the mod on the client, it's just way better that way - for the whistle hotkey alone!
